name: Deploy to heroku and run tests

on: [push, pull_request]
  branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
      
      - name: Run the tests
        run: npm run test

      - name: Build
        run: npm run build

      - uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: forums-app
          branch: master
